@startuml
title StructureIO - Activity Flow

start
:Retrieve Structure;
:Execute checkInitAtomCache;
:Set AtomCache;
:Retrieve AtomCache;
:Retrieve BiologicalAssembly;
:Retrieve BiologicalAssembly;
:Retrieve BiologicalAssembly;
:Retrieve BiologicalAssembly;
stop

@enduml